#!/usr/bin/env python

Import("env")
Import("env_modules")

env_trip_video = env_modules.Clone()
env_trip_video.add_source_files(env.modules_sources, "*.cpp")
if env["platform"] == "android":
    env_trip_video.Append(CPPPATH=["/home/rabienrose/Documents/code/ffmpeg-android-maker/output/include/arm64-v8a"])
    env.Append(LIBPATH=['/home/rabienrose/Documents/code/ffmpeg-android-maker/output/lib/arm64-v8a'])
    env.Append(LIBS=['swscale', 'avdevice', 'avformat', 'avcodec', 'avfilter', 'avutil', 'swresample'])
else:
    env_trip_video.Append(CPPPATH=["/home/rabienrose/ffmpeg_build/include"])
    env.Append(LIBPATH=['/home/rabienrose/ffmpeg_build/lib'])
    env.Append(LIBS=['swscale', 'avdevice', 'avformat', 'avcodec', 'avfilter', 'avutil', 'swresample', 'pthread', 'm', 'z', 'X11', 'vdpau', 'va', 'va-drm', 'va-x11'])